"use client";

import { ArrowRight, Check, Globe2, Scale, UserRound } from "lucide-react";
import { useState } from "react";
import { useAuth } from "../../components/auth-provider";

export default function Onboarding() {
  const { profile, updateProfile } = useAuth(); const [step,setStep]=useState(1); const [data,setData]=useState(profile); const [saving,setSaving]=useState(false);
  async function finish(){setSaving(true);await updateProfile({...data,onboardingComplete:true});window.location.assign("/dashboard");}
  return <main className="onboarding"><header><div className="brand"><Scale /><span>MĪZĀN</span></div><div className="step-track">{[1,2,3].map(n=><span key={n} className={step>=n?"active":""}>{step>n?<Check />:n}</span>)}</div></header><section className="onboarding-card"><span className="eyebrow">Step {step} of 3</span>{step===1&&<><UserRound className="onboarding-icon"/><h1>How will you use MĪZĀN?</h1><p>This helps us organise the dashboard without changing any religious ruling.</p><div className="choice-grid">{["Individual","Family representative","Student","Business owner","Mahallu / institution","Scholar / Qazi"].map(role=><button key={role} className={data.role===role?"selected":""} onClick={()=>setData({...data,role})}>{role}{data.role===role&&<Check/>}</button>)}</div></>}{step===2&&<><Scale className="onboarding-icon"/><h1>Select your madhhab</h1><p>Your selection will remain visible in every calculation and answer.</p><div className="choice-grid two">{["Hanafi","Maliki","Shafi'i","Hanbali"].map(madhhab=><button key={madhhab} className={data.madhhab===madhhab?"selected":""} onClick={()=>setData({...data,madhhab})}>{madhhab}{data.madhhab===madhhab&&<Check/>}</button>)}</div></>}{step===3&&<><Globe2 className="onboarding-icon"/><h1>Language and region</h1><p>Regional context helps flag questions that may involve local documents or law.</p><div className="onboarding-fields"><label><span>Preferred language</span><select value={data.language} onChange={e=>setData({...data,language:e.target.value})}><option>English</option><option>Malayalam</option><option>Arabic</option></select></label><label><span>Country or region</span><input value={data.region} onChange={e=>setData({...data,region:e.target.value})}/></label></div></>}<div className="onboarding-actions">{step>1&&<button className="ghost-button" onClick={()=>setStep(step-1)}>Back</button>}<button className="primary-button" onClick={()=>step<3?setStep(step+1):finish()}>{saving?"Saving…":step<3?"Continue":"Open dashboard"}<ArrowRight/></button></div></section></main>;
}
