"use client";

import { BadgeCheck, CalendarDays, Check, Languages, LocateFixed, Search, ShieldCheck, Users, Video } from "lucide-react";
import { useState } from "react";
import { AppShell } from "../../components/app-shell";
import { saveAppointment } from "../../lib/supabase";

const qazis=[{id:"prototype-1",name:"Qazi Abdul Rahman",institution:"Community Shariah Guidance Centre",place:"Malappuram, Kerala",languages:"Malayalam · Arabic · English",expertise:"Zakat · Farā’iḍ",madhhab:"Shafi'i · Hanafi"},{id:"prototype-2",name:"Dr. Muhammad Sameer",institution:"Islamic Finance Advisory Desk",place:"Kozhikode, Kerala",languages:"Malayalam · English · Urdu",expertise:"Business Zakat · Modern finance",madhhab:"All four madhhabs"},{id:"prototype-3",name:"Qazi Hasan Musliyar",institution:"Family Matters Review Office",place:"Kannur, Kerala",languages:"Malayalam · Arabic",expertise:"Inheritance · Family verification",madhhab:"Shafi'i"}];
export default function Qazi(){const [selected,setSelected]=useState(qazis[0]);const [date,setDate]=useState("");const [type,setType]=useState("Farā’iḍ verification");const [note,setNote]=useState("");const [toast,setToast]=useState("");async function book(){try{const r=await saveAppointment({qazi_reference:selected.id,consultation_type:type,preferred_date:date,notes:note});setToast(r.local?"Request saved on this device":"Request sent securely");}catch(e){setToast(e instanceof Error?e.message:"Could not save request");}}return <AppShell title="Qazi Connect" eyebrow="Qualified scholar consultation"><div className="tool-page-head"><div><span className="eyebrow"><ShieldCheck/> Verification network</span><h2>Connect the case to qualified human judgment.</h2><p>Filter by expertise, language, madhhab and consultation mode. Profiles below are clearly marked prototype data until real verification is completed.</p></div><div className="directory-search"><Search/><input placeholder="Search location or expertise"/><button><LocateFixed/>Kerala</button></div></div><div className="qazi-page"><section className="qazi-directory"><div className="filter-row"><button className="active">All expertise</button><button>Zakat</button><button>Farā’iḍ</button><button>Business</button><button>Online available</button></div><div className="qazi-list">{qazis.map(q=><article key={q.id} className={selected.id===q.id?"selected":""}><div className="qazi-avatar"><Users/></div><div className="qazi-info"><span><BadgeCheck/>Prototype profile</span><h3>{q.name}</h3><p>{q.institution}</p><div><small><LocateFixed/>{q.place}</small><small><Languages/>{q.languages}</small><small><ShieldCheck/>{q.madhhab}</small></div></div><aside><strong>{q.expertise}</strong><small><Video/> Online & in person</small><button onClick={()=>setSelected(q)}>{selected.id===q.id?<><Check/>Selected</>:"Select scholar"}</button></aside></article>)}</div></section><aside className="booking-panel"><span className="eyebrow">Consultation request</span><h3>{selected.name}</h3><p>{selected.institution}</p><label><span>Consultation type</span><select value={type} onChange={e=>setType(e.target.value)}><option>Farā’iḍ verification</option><option>Zakat consultation</option><option>Business Zakat assessment</option><option>Modern financial Mas’ala</option></select></label><label><span>Preferred date</span><div className="input-icon"><CalendarDays/><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div></label><label><span>Private note</span><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Briefly describe what requires review"/></label><div className="private-note"><ShieldCheck/>Do not upload sensitive documents until the scholar&apos;s identity is verified.</div><button className="primary-button full" disabled={!date} onClick={book}>Request appointment</button></aside></div>{toast&&<div className="toast">{toast}</div>}</AppShell>}
