export const zakatCopy = {
  en: {
    pageTitle: "Zakat Calculator",
    pageEyebrow: "Madhhab-aware guidance",
    saveDraft: "Save draft",
    saving: "Saving…",
    methodSuffix: "method selected",
    heroTitle: "Calculate your Zakat step by step.",
    heroText: "Enter each type of wealth, check the conditions, and then save the result or send it for qualified review.",
    steps: ["Wealth", "Conditions", "Result"],
    caseTitle: "Give this calculation a name",
    defaultTitle: "My annual Zakat calculation",
    step: "Step",
    step1Title: "Enter wealth that may be zakatable",
    cash: "Cash you hold",
    bank: "Money in bank accounts",
    gold: "Current value of gold",
    silver: "Current value of silver",
    business: "Goods held for sale",
    businessHelp: "Sale stock only—not permanent equipment used by the business",
    receivables: "Money you expect to receive",
    investments: "Shares and investments",
    digitalAssets: "Digital assets",
    other: "Other potentially zakatable wealth",
    sourceTitle: "Why are these separate?",
    step1Note: "Keeping each type separate makes the calculation easier to understand and allows a scholar to review how each asset should be treated.",
    step2Title: "Check debts, niṣāb and one lunar year",
    liabilities: "Debts due soon",
    liabilitiesHelp: "Enter only short-term debts that you want considered in this calculation.",
    nisab: "Today's niṣāb amount",
    nisabHelp: "Enter the current rupee value of the gold or silver standard you are following.",
    hawlTitle: "Has this wealth completed one lunar year?",
    hawlHelp: "Tick this only when the general ḥawl condition applies to this wealth.",
    nisabTitle: "What is niṣāb?",
    nisabText: "Niṣāb is the minimum wealth threshold for Zakat. Enter today's value based on the gold or silver standard you follow.",
    hawlInfoTitle: "What is ḥawl?",
    hawlInfoText: "Ḥawl generally means the wealth remained at or above niṣāb for one complete lunar year. Some asset types have different rules.",
    step2Note: "This gives a general 2.5% cash and trade-wealth estimate. Asset eligibility and madhhab differences still require qualified review.",
    step3Title: "Review your calculation",
    reviewNotes: "Items to review",
    ready: "The information entered meets the general niṣāb and ḥawl pathway.",
    scholarTitle: "Scholar verification required",
    scholarText: "This is an educational preliminary result, not an independent fatwa or final legal instruction.",
    back: "Back",
    continue: "Continue",
    updateCalculation: "Update calculation",
    saveCalculation: "Save calculation",
    liveResult: "Live preliminary result",
    estimatedZakat: "Estimated Zakat",
    totalAssets: "Total entered wealth",
    enteredLiabilities: "Debts entered",
    netWealth: "Net zakatable wealth",
    nisabLabel: "Niṣāb threshold",
    rate: "Rate used",
    madhhab: "Selected madhhab",
    notEntered: "Not entered",
    conditionsMet: "General conditions met",
    calculationPaused: "More information needed",
    eligibleHelp: "You can save this or request a qualified review.",
    pausedHelp: "Enter niṣāb and confirm whether ḥawl applies.",
    saveReview: "Save and request review",
    download: "Download calculation report",
    savedReview: "Calculation saved and sent for Qazi review.",
    saved: "Calculation saved securely.",
    saveError: "The calculation could not be saved.",
    openError: "This calculation could not be opened.",
    preparing: "Preparing your private calculation…",
  },
  ml: {
    pageTitle: "സകാത്ത് കാൽക്കുലേറ്റർ",
    pageEyebrow: "മദ്ഹബ് അനുസരിച്ചുള്ള മാർഗനിർദേശം",
    saveDraft: "ഡ്രാഫ്റ്റ് സേവ് ചെയ്യുക",
    saving: "സേവ് ചെയ്യുന്നു…",
    methodSuffix: "രീതി തിരഞ്ഞെടുത്തു",
    heroTitle: "സകാത്ത് ഘട്ടം ഘട്ടമായി കണക്കാക്കാം.",
    heroText: "ഓരോ തരത്തിലുള്ള സമ്പത്തും നൽകുക, നിബന്ധനകൾ പരിശോധിക്കുക, ശേഷം ഫലം സേവ് ചെയ്യുകയോ യോഗ്യനായ പണ്ഡിതന്റെ പരിശോധനയ്ക്ക് അയയ്ക്കുകയോ ചെയ്യാം.",
    steps: ["സമ്പത്ത്", "നിബന്ധനകൾ", "ഫലം"],
    caseTitle: "ഈ കണക്കിന് ഒരു പേര് നൽകുക",
    defaultTitle: "എന്റെ വാർഷിക സകാത്ത് കണക്ക്",
    step: "ഘട്ടം",
    step1Title: "സകാത്തിന് പരിഗണിക്കേണ്ട സമ്പത്ത് നൽകുക",
    cash: "കൈവശമുള്ള പണം",
    bank: "ബാങ്ക് അക്കൗണ്ടുകളിലെ പണം",
    gold: "സ്വർണത്തിന്റെ നിലവിലെ മൂല്യം",
    silver: "വെള്ളിയുടെ നിലവിലെ മൂല്യം",
    business: "വിൽപ്പനയ്ക്കായി സൂക്ഷിച്ച സാധനങ്ങൾ",
    businessHelp: "വിൽപ്പന സ്റ്റോക്ക് മാത്രം—വ്യാപാരത്തിന് ഉപയോഗിക്കുന്ന സ്ഥിര ഉപകരണങ്ങൾ അല്ല",
    receivables: "തിരികെ ലഭിക്കാനുള്ള പണം",
    investments: "ഓഹരികളും നിക്ഷേപങ്ങളും",
    digitalAssets: "ഡിജിറ്റൽ ആസ്തികൾ",
    other: "മറ്റു സകാത്ത് ബാധകമായ സമ്പത്ത്",
    sourceTitle: "ഇവ വേർതിരിച്ച് നൽകുന്നത് എന്തിന്?",
    step1Note: "ഓരോ സമ്പത്ത് വിഭാഗവും വേർതിരിച്ച് നൽകുന്നത് കണക്ക് എളുപ്പത്തിൽ മനസ്സിലാക്കാനും ഓരോ ആസ്തിയുടെയും വിധി പണ്ഡിതന് പരിശോധിക്കാനും സഹായിക്കുന്നു.",
    step2Title: "കടം, നിസാബ്, ഒരു ചാന്ദ്രവർഷം എന്നിവ പരിശോധിക്കുക",
    liabilities: "ഉടൻ അടയ്ക്കേണ്ട കടങ്ങൾ",
    liabilitiesHelp: "ഈ കണക്കിൽ പരിഗണിക്കേണ്ട ഹ്രസ്വകാല കടങ്ങൾ മാത്രം നൽകുക.",
    nisab: "ഇന്നത്തെ നിസാബ് തുക",
    nisabHelp: "നിങ്ങൾ പിന്തുടരുന്ന സ്വർണം അല്ലെങ്കിൽ വെള്ളി മാനദണ്ഡത്തിന്റെ ഇന്നത്തെ രൂപ മൂല്യം നൽകുക.",
    hawlTitle: "ഈ സമ്പത്തിന് ഒരു ചാന്ദ്രവർഷം പൂർത്തിയായോ?",
    hawlHelp: "ഈ സമ്പത്തിന് പൊതുവായ ഹൗൽ നിബന്ധന ബാധകമാണെങ്കിൽ മാത്രം ടിക്ക് ചെയ്യുക.",
    nisabTitle: "നിസാബ് എന്താണ്?",
    nisabText: "സകാത്ത് നിർബന്ധമാകുന്നതിനുള്ള കുറഞ്ഞ സമ്പത്ത് പരിധിയാണ് നിസാബ്. നിങ്ങൾ പിന്തുടരുന്ന സ്വർണം അല്ലെങ്കിൽ വെള്ളി മാനദണ്ഡത്തിന്റെ ഇന്നത്തെ മൂല്യം നൽകുക.",
    hawlInfoTitle: "ഹൗൽ എന്താണ്?",
    hawlInfoText: "സമ്പത്ത് നിസാബിന് തുല്യമോ അതിലധികമോ ആയി ഒരു പൂർണ്ണ ചാന്ദ്രവർഷം നിലനിൽക്കുന്നതാണ് പൊതുവായി ഹൗൽ. ചില സമ്പത്ത് വിഭാഗങ്ങൾക്ക് വ്യത്യസ്ത നിയമങ്ങൾ ഉണ്ടാകാം.",
    step2Note: "ഇത് പണത്തിന്റെയും വ്യാപാര സമ്പത്തിന്റെയും പൊതുവായ 2.5% പ്രാഥമിക കണക്കാണ്. ആസ്തിയുടെ യോഗ്യതയും മദ്ഹബ് വ്യത്യാസങ്ങളും യോഗ്യനായ പണ്ഡിതൻ പരിശോധിക്കണം.",
    step3Title: "നിങ്ങളുടെ കണക്ക് പരിശോധിക്കുക",
    reviewNotes: "പരിശോധിക്കേണ്ട കാര്യങ്ങൾ",
    ready: "നൽകിയ വിവരങ്ങൾ പൊതുവായ നിസാബ്, ഹൗൽ നിബന്ധനകൾ പൂർത്തിയാക്കുന്നു.",
    scholarTitle: "പണ്ഡിതന്റെ പരിശോധന ആവശ്യമാണ്",
    scholarText: "ഇത് വിദ്യാഭ്യാസ ആവശ്യത്തിനുള്ള പ്രാഥമിക ഫലമാണ്; സ്വതന്ത്ര ഫത്‌വയോ അന്തിമ നിയമനിർദേശമോ അല്ല.",
    back: "പിന്നിലേക്ക്",
    continue: "തുടരുക",
    updateCalculation: "കണക്ക് പുതുക്കുക",
    saveCalculation: "കണക്ക് സേവ് ചെയ്യുക",
    liveResult: "തത്സമയ പ്രാഥമിക ഫലം",
    estimatedZakat: "കണക്കാക്കിയ സകാത്ത്",
    totalAssets: "നൽകിയ ആകെ സമ്പത്ത്",
    enteredLiabilities: "നൽകിയ കടങ്ങൾ",
    netWealth: "സകാത്തിന് പരിഗണിക്കുന്ന ശുദ്ധ സമ്പത്ത്",
    nisabLabel: "നിസാബ് പരിധി",
    rate: "ഉപയോഗിച്ച നിരക്ക്",
    madhhab: "തിരഞ്ഞെടുത്ത മദ്ഹബ്",
    notEntered: "നൽകിയിട്ടില്ല",
    conditionsMet: "പൊതുവായ നിബന്ധനകൾ പൂർത്തിയായി",
    calculationPaused: "കൂടുതൽ വിവരങ്ങൾ ആവശ്യമാണ്",
    eligibleHelp: "ഇത് സേവ് ചെയ്യുകയോ പരിശോധനയ്ക്ക് അയയ്ക്കുകയോ ചെയ്യാം.",
    pausedHelp: "നിസാബ് നൽകുകയും ഹൗൽ ബാധകമാണോ എന്ന് രേഖപ്പെടുത്തുകയും ചെയ്യുക.",
    saveReview: "സേവ് ചെയ്ത് പരിശോധനയ്ക്ക് അയയ്ക്കുക",
    download: "കണക്കിന്റെ റിപ്പോർട്ട് ഡൗൺലോഡ് ചെയ്യുക",
    savedReview: "കണക്ക് സേവ് ചെയ്ത് ഖാസിയുടെ പരിശോധനയ്ക്ക് അയച്ചു.",
    saved: "കണക്ക് സുരക്ഷിതമായി സേവ് ചെയ്തു.",
    saveError: "കണക്ക് സേവ് ചെയ്യാൻ കഴിഞ്ഞില്ല.",
    openError: "ഈ കണക്ക് തുറക്കാൻ കഴിഞ്ഞില്ല.",
    preparing: "നിങ്ങളുടെ സ്വകാര്യ കണക്ക് തയ്യാറാക്കുന്നു…",
  },
} as const;

export const zakatCategoryLabels = {
  en: { cash: "Cash", bank: "Bank accounts", gold: "Gold", silver: "Silver", business: "Goods held for sale", receivables: "Money to receive", investments: "Investments", digitalAssets: "Digital assets", other: "Other wealth" },
  ml: { cash: "കൈവശമുള്ള പണം", bank: "ബാങ്ക് പണം", gold: "സ്വർണം", silver: "വെള്ളി", business: "വ്യാപാര സാധനങ്ങൾ", receivables: "ലഭിക്കാനുള്ള പണം", investments: "നിക്ഷേപങ്ങൾ", digitalAssets: "ഡിജിറ്റൽ ആസ്തികൾ", other: "മറ്റു സമ്പത്ത്" },
} as const;

export const zakatIssueMalayalam: Record<string, string> = {
  "The ḥawl condition is not confirmed for this calculation.": "ഈ കണക്കിന് ഹൗൽ നിബന്ധന സ്ഥിരീകരിച്ചിട്ടില്ല.",
  "Enter a current niṣāb reference before relying on the result.": "ഫലം ആശ്രയിക്കുന്നതിന് മുമ്പ് ഇന്നത്തെ നിസാബ് തുക നൽകുക.",
  "Digital-asset ownership, liquidity and valuation require category review.": "ഡിജിറ്റൽ ആസ്തികളുടെ ഉടമസ്ഥത, പണമായി മാറ്റാനുള്ള സൗകര്യം, മൂല്യനിർണയം എന്നിവ പ്രത്യേകം പരിശോധിക്കണം.",
  "Investment treatment can depend on the asset and investment intention.": "നിക്ഷേപത്തിന്റെ വിധി ആസ്തിയുടെ സ്വഭാവത്തെയും നിക്ഷേപ ലക്ഷ്യത്തെയും ആശ്രയിച്ചിരിക്കും.",
  "Receivables should be reviewed for recoverability.": "ലഭിക്കാനുള്ള പണം യഥാർത്ഥത്തിൽ തിരികെ ലഭിക്കുമോ എന്ന് പരിശോധിക്കണം.",
};
