"use client";

import { ArrowRight, BadgeCheck, Bot, Search, Send, ShieldCheck, Sparkles } from "lucide-react";
import { useState } from "react";
import { AppShell } from "../../components/app-shell";
import { ScholarNotice, SourceNote } from "../../components/ui";
import { useAuth } from "../../components/auth-provider";

const samples=[{q:"Is zakat payable on money in a digital wallet?",a:"Accessible digital-wallet balances are generally treated like cash and combined with other zakatable wealth. Niṣāb, ownership and ḥawl still require madhhab-aware review.",s:"General cash-zakat principles; Qur’an 9:103. Verify asset access and ownership."},{q:"Is a bank nominee automatically an Islamic heir?",a:"A nominee may receive or manage funds under local paperwork, but that alone does not determine the Islamic heirs. The complete estate and family tree must be reviewed.",s:"Farā’iḍ principles in Qur’an 4:11–12; local documents require qualified review."},{q:"What should an online business include for Zakat?",a:"A business review normally considers sale inventory, business cash and recoverable receivables, then examines deductible short-term obligations.",s:"Classical trade-goods principles; category treatment can differ by madhhab."},{q:"Can AI be used for Islamic learning?",a:"AI can support search, organisation and preliminary learning when sources are checked. It should not replace a qualified scholar in personal or disputed cases.",s:"Educational guidance principle; all generated conclusions require source verification."}];
export default function Masail(){const {profile}=useAuth();const [selected,setSelected]=useState(samples[0]);const [query,setQuery]=useState("");const filtered=samples.filter(x=>x.q.toLowerCase().includes(query.toLowerCase()));return <AppShell title="Masā’il Assistant" eyebrow="Source-noted preliminary guidance"><div className="tool-page-head"><div><span className="eyebrow"><Sparkles/> {profile.madhhab} guidance mode</span><h2>Ask carefully. Understand the limits.</h2><p>MĪZĀN organises approved guidance, asks follow-up questions and refers personal or disputed matters to a scholar.</p></div></div><div className="assistant-page"><aside className="question-library"><div className="search-box"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search suggested questions"/></div><span className="list-label">Suggested modern doubts</span>{filtered.map(item=><button key={item.q} className={selected.q===item.q?"active":""} onClick={()=>setSelected(item)}><span>{item.q}</span><ArrowRight/></button>)}</aside><section className="assistant-conversation"><div className="assistant-status"><span><Bot/>MĪZĀN Assistant</span><b><i/>Scholar-approved demo library</b></div><div className="user-bubble">{selected.q}</div><article className="assistant-answer"><span><Sparkles/>Preliminary answer</span><h3>{selected.q}</h3><p>{selected.a}</p><SourceNote>{selected.s}</SourceNote><div className="answer-meta"><span><BadgeCheck/> Madhhab: {profile.madhhab}</span><span><ShieldCheck/> Confidence: Requires context</span></div></article><ScholarNotice compact/><div className="ask-bar"><input placeholder="Ask a new question…"/><button aria-label="Send question"><Send/></button></div></section></div></AppShell>}
