"use client";

import { ArrowRight, Check, CircleDollarSign, FileDown, Save, Scale, ShieldCheck } from "lucide-react";
import { useMemo, useState } from "react";
import { AppShell } from "../../components/app-shell";
import { ScholarNotice, SourceNote } from "../../components/ui";
import { useAuth } from "../../components/auth-provider";
import { saveCase } from "../../lib/supabase";

const format = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 });
export default function ZakatPage(){
 const {profile}=useAuth(); const [toast,setToast]=useState(""); const [data,setData]=useState({cash:90000,gold:25000,business:10000,receivables:0,investments:0,liabilities:15000,nisab:82000,hawl:true});
 const assets=useMemo(()=>data.cash+data.gold+data.business+data.receivables+data.investments,[data]); const net=Math.max(0,assets-data.liabilities); const due=data.hawl&&net>=data.nisab?net*.025:0;
 function field(label:string,key:keyof typeof data){return <label><span>{label}</span><div className="money-field"><b>₹</b><input type="number" min="0" value={Number(data[key])} onChange={e=>setData({...data,[key]:Math.max(0,Number(e.target.value)||0)})}/></div></label>}
 async function save(){try{const result=await saveCase("zakat",profile.madhhab,data,{assets,net,due});setToast(result.local?"Saved on this device":"Saved securely to Supabase");}catch(e){setToast(e instanceof Error?e.message:"Could not save");}}
 return <AppShell title="Zakat Intelligence" eyebrow="Madhhab-aware calculation" actions={<button className="ghost-button compact" onClick={save}><Save/>Save draft</button>}><div className="tool-page-head"><div><span className="eyebrow"><ShieldCheck/> {profile.madhhab} method selected</span><h2>Calculate your zakatable wealth</h2><p>Enter each category separately. MĪZĀN will show the preliminary calculation and what requires scholar review.</p></div><div className="step-pills"><span className="active"><Check/>Assets</span><span>2 Deductions</span><span>3 Result</span></div></div><div className="calculator-layout"><section className="workspace-panel calculator-form"><div className="panel-heading"><div><span>Step 1</span><h3>Wealth and obligations</h3></div><Scale/></div><div className="calculation-fields">{field("Cash and bank balances","cash")}{field("Gold and silver value","gold")}{field("Business inventory","business")}{field("Recoverable receivables","receivables")}{field("Shares and investments","investments")}{field("Reviewable liabilities","liabilities")}{field("Current niṣāb reference","nisab")}</div><label className="check-card"><input type="checkbox" checked={data.hawl} onChange={e=>setData({...data,hawl:e.target.checked})}/><span><strong>A lunar year (ḥawl) has passed</strong><small>Some wealth categories may have separate conditions.</small></span></label><SourceNote>Prototype applies the general 2.5% cash/trade-goods rate after niṣāb and ḥawl. Madhhab differences and asset eligibility need approved sources.</SourceNote></section><aside className="result-panel"><span className="eyebrow">Preliminary result</span><div className="result-orb"><CircleDollarSign/><div><small>Estimated Zakat</small><strong>{format.format(due)}</strong></div></div><dl><div><dt>Total assets</dt><dd>{format.format(assets)}</dd></div><div><dt>Liabilities</dt><dd>− {format.format(data.liabilities)}</dd></div><div><dt>Net zakatable wealth</dt><dd>{format.format(net)}</dd></div><div><dt>Rate used</dt><dd>2.5%</dd></div><div><dt>Madhhab</dt><dd>{profile.madhhab}</dd></div></dl><ScholarNotice compact/><button className="primary-button full" onClick={save}>Save calculation <ArrowRight/></button><button className="text-button"><FileDown/>Download report preview</button></aside></div>{toast&&<div className="toast">{toast}</div>}</AppShell>
}
