"use client";

import { AlertTriangle, ArrowLeft, ArrowRight, Check, FileDown, GitBranch, Plus, Save, Send, ShieldCheck, Trash2, UserRound, Users } from "lucide-react";
import { useSearchParams } from "next/navigation";
import { Suspense, useEffect, useMemo, useState } from "react";
import { AppShell } from "../../components/app-shell";
import { ReviewWarning, ScholarNotice, SourceNote } from "../../components/ui";
import { useAuth } from "../../components/auth-provider";
import { calculateBasicFaraid, type EstateItem, type FaraidInput, type ObligationItem, type RelativeItem } from "../../lib/calculations";
import { createCase, getCase, updateCase } from "../../lib/supabase";
import type { CaseRecord, VerificationStatus } from "../../lib/models";
import { downloadCaseReport } from "../../lib/reporting";

const money = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 });
const initial: FaraidInput = {
  deceasedName: "", deceasedGender: "male", dateOfDeath: "", country: "India",
  assets: [{ id: "asset-1", label: "", category: "Cash / bank", value: 0, ownershipPercent: 100 }],
  obligations: [{ id: "obligation-1", label: "", category: "Debt", value: 0 }], bequest: 0,
  relatives: [],
};
const relationshipLabels: Record<string, string> = { wife: "Wife", husband: "Husband", mother: "Mother", father: "Father", son: "Son", daughter: "Daughter", grandson: "Grandson", granddaughter: "Granddaughter", brother: "Brother", sister: "Sister", other: "Other relative" };

function FaraidWorkspace() {
  const params = useSearchParams();
  const { profile, user } = useAuth();
  const [step, setStep] = useState(1);
  const [title, setTitle] = useState("Private family estate case");
  const [data, setData] = useState<FaraidInput>(initial);
  const [record, setRecord] = useState<CaseRecord | null>(null);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const result = useMemo(() => calculateBasicFaraid(data), [data]);

  useEffect(() => {
    const id = params.get("case"); if (!id) return;
    void getCase(id).then(row => { if (!row || row.case_type !== "faraid") return; setRecord(row); setTitle(row.title); setData({ ...initial, ...(row.input_data as unknown as FaraidInput) }); }).catch(reason => setError(reason instanceof Error ? reason.message : "Could not open this case."));
  }, [params]);

  function updateAsset(id: string, patch: Partial<EstateItem>) { setData(current => ({ ...current, assets: current.assets.map(item => item.id === id ? { ...item, ...patch } : item) })); }
  function updateObligation(id: string, patch: Partial<ObligationItem>) { setData(current => ({ ...current, obligations: current.obligations.map(item => item.id === id ? { ...item, ...patch } : item) })); }
  function updateRelative(id: string, patch: Partial<RelativeItem>) { setData(current => ({ ...current, relatives: current.relatives.map(item => item.id === id ? { ...item, ...patch } : item) })); }
  function addRelative() { setData(current => ({ ...current, relatives: [...current.relatives, { id: crypto.randomUUID(), label: "", relationship: "son", gender: "male", count: 1, aliveAtDeath: true, relationshipType: "biological", disputed: false }] })); }

  async function persist(status: VerificationStatus = record?.verification_status || "unverified") {
    setSaving(true); setMessage(""); setError("");
    try {
      const stored = record
        ? await updateCase(record.id, { title, input_data: data as unknown as Record<string, unknown>, result_data: result as unknown as Record<string, unknown>, verification_status: status })
        : await createCase({ caseType: "faraid", madhhab: profile.madhhab, title, input: data as unknown as Record<string, unknown>, result: result as unknown as Record<string, unknown>, status });
      setRecord(stored); window.history.replaceState({}, "", `/faraid/?case=${stored.id}`);
      setMessage(status === "review_requested" ? "Case saved and marked for qualified review." : "Private estate case saved.");
      return stored;
    } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not save this case."); return null; }
    finally { setSaving(false); }
  }

  function download() {
    const current: CaseRecord = record || { id: "unsaved", user_id: user?.id || "", case_type: "faraid", madhhab: "shafii", title, currency: "INR", input_data: data as unknown as Record<string, unknown>, result_data: result as unknown as Record<string, unknown>, verification_status: "unverified", reviewer_note: null, created_at: new Date().toISOString(), updated_at: new Date().toISOString() };
    downloadCaseReport({ ...current, title, input_data: data as unknown as Record<string, unknown>, result_data: result as unknown as Record<string, unknown> });
  }

  return <AppShell title="MĪZĀN Farā’iḍ" eyebrow="Private inheritance workspace" actions={<button className="ghost-button compact" onClick={() => void persist()} disabled={saving}><Save/>{saving ? "Saving…" : "Save case"}</button>}>
    <div className="tool-page-head"><div><span className="eyebrow"><ShieldCheck/> {profile.madhhab} case</span><h2>Build the estate before dividing it.</h2><p>Record the deceased person, ownership, prior obligations and family relationships. Unsupported patterns are paused instead of guessed.</p></div><div className="step-pills faraid-steps">{["Person", "Estate", "Family", "Result"].map((label, index) => <button key={label} className={step === index + 1 ? "active" : step > index + 1 ? "done" : ""} onClick={() => setStep(index + 1)}>{step > index + 1 ? <Check/> : index + 1} {label}</button>)}</div></div>
    {error && <div className="form-error workspace-error">{error}</div>}
    <div className="faraid-workspace"><section className="workspace-panel faraid-wizard"><label className="case-title-field"><span>Private case title</span><input value={title} onChange={event => setTitle(event.target.value)} maxLength={90}/></label>
      {step === 1 && <><div className="panel-heading"><div><span>Step 1</span><h3>Deceased person’s details</h3></div><UserRound/></div><div className="settings-fields deceased-fields"><label><span>Name or private identification label</span><input value={data.deceasedName} onChange={event => setData({ ...data, deceasedName: event.target.value })} placeholder="e.g. Family estate A"/></label><label><span>Gender</span><select value={data.deceasedGender} onChange={event => setData({ ...data, deceasedGender: event.target.value as FaraidInput["deceasedGender"] })}><option value="male">Male</option><option value="female">Female</option></select></label><label><span>Date of death</span><input type="date" value={data.dateOfDeath} onChange={event => setData({ ...data, dateOfDeath: event.target.value })}/></label><label><span>Country or region</span><input value={data.country} onChange={event => setData({ ...data, country: event.target.value })}/></label></div><div className="private-note"><ShieldCheck/>Use a private label if you do not want to store a full name.</div></>}
      {step === 2 && <><div className="panel-heading"><div><span>Step 2</span><h3>Estate assets and prior obligations</h3></div><GitBranch/></div><div className="entry-list"><div className="entry-list-head"><strong>Owned assets</strong><button onClick={() => setData(current => ({ ...current, assets: [...current.assets, { id: crypto.randomUUID(), label: "", category: "Property", value: 0, ownershipPercent: 100 }] }))}><Plus/>Add asset</button></div>{data.assets.map(item => <article key={item.id}><input aria-label="Asset description" value={item.label} onChange={event => updateAsset(item.id, { label: event.target.value })} placeholder="Description"/><select aria-label="Asset category" value={item.category} onChange={event => updateAsset(item.id, { category: event.target.value })}><option>Cash / bank</option><option>Gold / silver</option><option>Property</option><option>Business</option><option>Investment</option><option>Receivable</option><option>Digital asset</option><option>Other</option></select><input aria-label="Asset value" type="number" min="0" value={item.value} onChange={event => updateAsset(item.id, { value: Math.max(0, Number(event.target.value) || 0) })}/><div className="percent-input"><input aria-label="Ownership percent" type="number" min="0" max="100" value={item.ownershipPercent} onChange={event => updateAsset(item.id, { ownershipPercent: Math.min(100, Math.max(0, Number(event.target.value) || 0)) })}/><span>% owned</span></div><button className="danger-icon" aria-label="Remove asset" onClick={() => setData(current => ({ ...current, assets: current.assets.filter(row => row.id !== item.id) }))}><Trash2/></button></article>)}</div>
        <div className="entry-list obligations-list"><div className="entry-list-head"><strong>Prior obligations</strong><button onClick={() => setData(current => ({ ...current, obligations: [...current.obligations, { id: crypto.randomUUID(), label: "", category: "Debt", value: 0 }] }))}><Plus/>Add obligation</button></div>{data.obligations.map(item => <article key={item.id}><input aria-label="Obligation description" value={item.label} onChange={event => updateObligation(item.id, { label: event.target.value })} placeholder="Description"/><select aria-label="Obligation category" value={item.category} onChange={event => updateObligation(item.id, { category: event.target.value })}><option>Debt</option><option>Funeral expense</option><option>Unpaid obligation</option><option>Business liability</option><option>Ownership adjustment</option><option>Other</option></select><input aria-label="Obligation value" type="number" min="0" value={item.value} onChange={event => updateObligation(item.id, { value: Math.max(0, Number(event.target.value) || 0) })}/><button className="danger-icon" aria-label="Remove obligation" onClick={() => setData(current => ({ ...current, obligations: current.obligations.filter(row => row.id !== item.id) }))}><Trash2/></button></article>)}</div><label className="bequest-field"><span>Entered bequest amount for review</span><div className="money-field"><b>₹</b><input type="number" min="0" value={data.bequest} onChange={event => setData({ ...data, bequest: Math.max(0, Number(event.target.value) || 0) })}/></div><small>Validity, recipient and the one-third limit require verification.</small></label><SourceNote>The net estate is calculated only after owned shares, debts, funeral costs and entered obligations are mapped.</SourceNote></>}
      {step === 3 && <><div className="panel-heading"><div><span>Step 3</span><h3>Family relationship map</h3></div><Users/></div><div className="relative-editor"><div className="entry-list-head"><strong>Relatives alive at the date of death</strong><button onClick={addRelative}><Plus/>Add relative</button></div>{data.relatives.length ? data.relatives.map(relative => <article key={relative.id}><div className="relative-primary"><input value={relative.label} onChange={event => updateRelative(relative.id, { label: event.target.value })} placeholder="Name or private label"/><select value={relative.relationship} onChange={event => updateRelative(relative.id, { relationship: event.target.value, gender: ["wife", "mother", "daughter", "granddaughter", "sister"].includes(event.target.value) ? "female" : ["husband", "father", "son", "grandson", "brother"].includes(event.target.value) ? "male" : "unspecified" })}>{Object.entries(relationshipLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><label><span>Count</span><input type="number" min="1" max="30" value={relative.count} onChange={event => updateRelative(relative.id, { count: Math.max(1, Number(event.target.value) || 1) })}/></label><button className="danger-icon" aria-label="Remove relative" onClick={() => setData(current => ({ ...current, relatives: current.relatives.filter(row => row.id !== relative.id) }))}><Trash2/></button></div><div className="relative-options"><label><input type="checkbox" checked={relative.aliveAtDeath} onChange={event => updateRelative(relative.id, { aliveAtDeath: event.target.checked })}/>Alive at death</label><label><input type="checkbox" checked={relative.disputed} onChange={event => updateRelative(relative.id, { disputed: event.target.checked })}/>Relationship disputed</label><select value={relative.relationshipType} onChange={event => updateRelative(relative.id, { relationshipType: event.target.value as RelativeItem["relationshipType"] })}><option value="biological">Biological</option><option value="marital">Marital</option><option value="adopted">Adopted</option><option value="foster">Foster</option><option value="step">Step</option><option value="other">Other</option></select></div></article>) : <div className="real-empty compact-empty"><Users/><strong>No relatives added</strong><p>Add each relationship separately. The calculation will not assume missing heirs.</p></div>}</div><div className="family-tree-live"><div className="tree-root"><UserRound/><strong>{data.deceasedName || "Deceased person"}</strong><small>{data.dateOfDeath || "Date not entered"}</small></div><div className="tree-branches">{data.relatives.map(relative => <div key={relative.id} className={relative.disputed ? "disputed" : !relative.aliveAtDeath ? "inactive" : ""}><UserRound/><strong>{relative.label || relationshipLabels[relative.relationship]}</strong><small>{relationshipLabels[relative.relationship]} · {relative.count}</small></div>)}</div></div></>}
      {step === 4 && <><div className="panel-heading"><div><span>Step 4</span><h3>Validation and preliminary shares</h3></div>{result.supported ? <Check/> : <AlertTriangle/>}</div><div className="estate-summary"><div><span>Total owned estate</span><strong>{money.format(result.grossEstate)}</strong></div><div><span>Prior obligations</span><strong>− {money.format(result.obligations)}</strong></div><div><span>Applied bequest</span><strong>− {money.format(result.appliedBequest)}</strong></div><div className="net"><span>Net distributable estate</span><strong>{money.format(result.netEstate)}</strong></div></div>{result.issues.length > 0 && <div className="issue-list"><strong><AlertTriangle/>Validation notes</strong>{result.issues.map(issue => <p key={issue}>{issue}</p>)}</div>}{result.supported ? <div className="share-table detailed-shares">{result.rows.map(row => <div key={row.label}><span><strong>{row.label}</strong><small>{row.relationship} · {row.fraction}</small><em>{row.reason}</em></span><b>{row.percentage.toFixed(2)}%<small>{money.format(row.amount)}</small></b></div>)}</div> : <ReviewWarning>Automatic division is paused. Save the complete family map and request qualified review; no unsupported share is guessed.</ReviewWarning>}<ScholarNotice/></>}
      <div className="wizard-actions">{step > 1 && <button className="ghost-button" onClick={() => setStep(step - 1)}><ArrowLeft/>Back</button>}<span/>{step < 4 ? <button className="primary-button" onClick={() => setStep(step + 1)}>Continue<ArrowRight/></button> : <button className="primary-button" onClick={() => void persist()} disabled={saving}><Save/>{record ? "Update case" : "Save case"}</button>}</div>
    </section>
    <aside className="faraid-summary glass-result"><span className="eyebrow">Live estate summary</span><strong>{money.format(result.netEstate)}</strong><small>Net distributable estate</small><dl><div><dt>Assets entered</dt><dd>{data.assets.length}</dd></div><div><dt>Obligations entered</dt><dd>{data.obligations.length}</dd></div><div><dt>Relatives mapped</dt><dd>{data.relatives.reduce((sum, item) => sum + item.count, 0)}</dd></div><div><dt>Automatic pathway</dt><dd>{result.supported ? "Available" : "Review needed"}</dd></div></dl><button className="primary-button full" onClick={() => void persist("review_requested")} disabled={saving}><Send/>Save & request review</button><button className="text-button" onClick={download}><FileDown/>Download case report</button><div className="private-note"><ShieldCheck/>Sharing with a Qazi requires separate consent during appointment booking.</div></aside></div>
    {message && <div className="toast"><Check/>{message}</div>}
  </AppShell>;
}

export default function Faraid() {
  return <Suspense fallback={<AppShell title="MĪZĀN Farā’iḍ" eyebrow="Private inheritance workspace"><div className="workspace-panel panel-loading">Preparing your private estate case…</div></AppShell>}><FaraidWorkspace/></Suspense>;
}
