"use client";

import Link from "next/link";
import { ArrowRight, Bot, Calculator, CalendarDays, FileCheck2, GitBranch, Plus, ShieldCheck, Users, WalletCards } from "lucide-react";
import { AppShell, StatCard } from "../../components/app-shell";
import { useAuth } from "../../components/auth-provider";

export default function Dashboard() {
  const { profile } = useAuth();
  return <AppShell title={`Assalāmu ʿalaykum, ${profile.fullName.split(" ")[0]}`} eyebrow="Workspace overview" actions={<Link className="primary-button compact" href="/zakat"><Plus/>New calculation</Link>}>
    <div className="dashboard-welcome"><div><span><ShieldCheck/> {profile.madhhab} workspace active</span><h2>Continue with clarity.</h2><p>Your calculations, reports and scholar consultations remain organised in one private workspace.</p></div><div className="welcome-balance"><small>Current prototype status</small><strong>Ready for review</strong><span>Supabase sync activates when project keys are connected.</span></div></div>
    <div className="stat-grid"><StatCard icon={WalletCards} label="Zakat records" value="3" detail="1 draft this year"/><StatCard icon={GitBranch} label="Farā’iḍ cases" value="1" detail="Awaiting verification" tone="blue"/><StatCard icon={CalendarDays} label="Consultations" value="2" detail="1 upcoming" tone="amber"/><StatCard icon={FileCheck2} label="Verified reports" value="0" detail="Prototype workspace" tone="violet"/></div>
    <div className="dashboard-grid"><section className="workspace-panel"><div className="panel-heading"><div><span>Start a workflow</span><h3>What do you need today?</h3></div></div><div className="quick-actions"><Link href="/zakat"><span className="teal"><Calculator/></span><div><strong>Calculate Zakat</strong><small>Cash, gold, business and receivables</small></div><ArrowRight/></Link><Link href="/faraid"><span className="blue"><GitBranch/></span><div><strong>Open a Farā’iḍ case</strong><small>Estate, obligations and family tree</small></div><ArrowRight/></Link><Link href="/masail"><span className="violet"><Bot/></span><div><strong>Ask a Mas’ala</strong><small>Modern preliminary guidance</small></div><ArrowRight/></Link><Link href="/qazi"><span className="amber"><Users/></span><div><strong>Find a Qazi</strong><small>Request scholar verification</small></div><ArrowRight/></Link></div></section><section className="workspace-panel"><div className="panel-heading"><div><span>Recent activity</span><h3>Cases and consultations</h3></div><Link href="/reports">View all</Link></div><div className="activity-list"><article><span className="teal"><Calculator/></span><div><strong>Annual Zakat calculation</strong><small>Updated today · {profile.madhhab}</small></div><b>Draft</b></article><article><span className="blue"><GitBranch/></span><div><strong>Family estate review</strong><small>Updated 2 days ago</small></div><b className="review">Review</b></article><article><span className="amber"><CalendarDays/></span><div><strong>Farā’iḍ consultation</strong><small>25 July · Online</small></div><b className="booked">Booked</b></article></div></section></div>
    <div className="dashboard-grid lower"><section className="workspace-panel"><div className="panel-heading"><div><span>Progress</span><h3>Verification pathway</h3></div></div><div className="verification-path"><div className="done"><span>1</span><strong>Case created</strong></div><i/><div className="current"><span>2</span><strong>Information review</strong></div><i/><div><span>3</span><strong>Qazi verification</strong></div><i/><div><span>4</span><strong>Approved report</strong></div></div></section><section className="safety-panel"><ShieldCheck/><div><strong>Important guidance</strong><p>Automatic calculations are educational. Verify complex or disputed cases before acting or distributing funds.</p></div></section></div>
  </AppShell>;
}
